
services:

  postgres:
    image: postgres:15
    container_name: fleet-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - fleet-network

  redis:
    image: redis:7
    container_name: fleet-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - fleet-network

  discovery-server:
    build: ./discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    networks:
      - fleet-network
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost:8761" ]
      interval: 10s
      timeout: 5s
      retries: 10

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      discovery-server:
        condition: service_healthy
    networks:
      - fleet-network

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - discovery-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${AUTH_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_URL}
    networks:
      - fleet-network

  vehicle-service:
    build: ./vehicle-service
    container_name: vehicle-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - redis
      - discovery-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${VEHICLE_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

      SPRING_DATA_REDIS_HOST: ${REDIS_HOST}
      SPRING_DATA_REDIS_PORT: ${REDIS_PORT}
      JWT_SECRET: ${JWT_SECRET}

      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_URL}
    networks:
      - fleet-network

  driver-service:
    build: ./driver-service
    container_name: driver-service
    ports:
      - "8083:8083"
    depends_on:
      - postgres
      - redis
      - discovery-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DRIVER_DB}
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345

      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka
    networks:
      - fleet-network

  tracking-service:
    build: ./tracking-service
    container_name: tracking-service
    ports:
      - "8084:8084"
    depends_on:
      - redis
      - discovery-server
    environment:
      SPRING_DATA_REDIS_HOST: ${REDIS_HOST}
      SPRING_DATA_REDIS_PORT: ${REDIS_PORT}

      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_URL}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - fleet-network

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "8085:8085"
    depends_on:
      - redis
      - discovery-server
    environment:
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka
    networks:
      - fleet-network

volumes:
  postgres_data:

networks:
  fleet-network: