spring.application.name=tracking-service
server.port=8084

# =====================
# EUREKA
# =====================
eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# =====================
# REDIS
# =====================
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

# =====================
# JWT
# =====================
jwt.secret=${JWT_SECRET}

# =====================
# ACTUATOR
# =====================
management.endpoints.web.exposure.include=*

# =====================
# SWAGGER
# =====================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html