spring.application.name=driver-service
server.port=8083

spring.datasource.url=jdbc:postgresql://postgres:5432/driver_db
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=${EUREKA_URL}
jwt.secret=${JWT_SECRET}
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html