spring.application.name=driver-service
server.port=8083

spring.datasource.url=jdbc:postgresql://postgres:5432/driver_db
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
jwt.secret=7f3c9b2a6d91e4c8a0f5d3b7e2c1a9f8d6b4c3e1a0f9d8c7b6a5e4d3c2b1a0
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html